[pytest]
testpaths =
    test-projects

python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: smoke tests
    regression: regression tests
    sanity: sanity tests
    ui: UI tests
    api: API tests
    mobile: mobile tests
    critical: critical business tests
    negative: negative tests
    integration: integration tests
    e2e: end-to-end tests
    setup: setup validation tests

addopts =
    -ra
    --strict-markers
    --disable-warnings